annBM <- function(...) .Defunct("getBM","biomaRt")
vennSelectBM <- function(...) .Defunct("makeVenn")
limma2biomaRt <- function(...) .Defunct("limma2biomart is defunct, see Refactoring Affycoretools vignette\n")
probes2tableBM <- function(...) .Defunct("getBM","biomaRt")
foldFiltBM <- function(...) .Defunct("getBM", "biomaRt")
foldFilt <- function(...) .Defunct("HTMLReport","ReportingTools")
vennSelectFC <- function(...) .Defunct("makeVenn")
hyperG2annaffy <- function(...) .Defunct("makeGoTable")
hyperGoutput <- function(...) .Defunct("makeGoTable")
limma2annaffy <- function(...) .Defunct("limma2annaffy is defunct, see Refactoring Affycoretools vignette\n")
probes2table <- function(...) .Defunct("probes2table is defunct, see Refactoring Affycoretools vignette\n")
vennSelect <- function(...) .Defunct("makeVenn")
